package: demo_base
version: 3.1.0
author: 'Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/demo_base'
page:
    title: 'translate:demo_base_title'
    perm: 'demo_base[]'
    pjax: true
    subpages:
        install: { title: 'translate:title' }
requires:
    packages:
        backup: ^2.3.0
        structure/content: ^2.7.0
        markitup: ^3.7.4
        phpmailer: ^2.5.1
        redactor: ^2.3.0
        sprog: ^1.5.1
        yform: ^4.1.1
    redaxo: ^5.9.0
    php:
        version: '>=7.4, <8.3'
console_commands:
    'demo_base:install': rex_command_demo_base_install
    'demo_base:dump_files': rex_command_demo_base_dumpfiles
    'demo_base:dump_tables': rex_command_demo_base_dumptables
setup:
    packages:
        markitup: 4864
        redactor: 3841
        sprog: 4720
        yform: 4941
    installSequence:
        - backup
        - structure/content
        - phpmailer
        - markitup
        - redactor
        - sprog
        - yform
    dbimport:
        - demo_base.utf8.sql
    fileimport:
        - demo_base.tar.gz
